default_language_version:
  node: 22.19.0

# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    # Use the sha / tag you want to point at, this needs
    # to stay in sync with the package.json version
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.3.3
        args: [--write, --list-different]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-added-large-files
        exclude: (yarn.lock|.yarn/|.pnp.cjs)
      - id: check-json
        exclude: (.vscode/|tsconfig.json|.devcontainer/devcontainer.json)
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-yaml
        files: (yaml$|yml$)
  - repo: local
    hooks:
      - id: eslint
        name: Eslint
        description: 'Run static code linting'
        entry: yarn lint --fix
        language: node
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
